# https://www.appveyor.com/docs/appveyor-yml/

version: "{build}"

init:
  - git config --global core.autocrlf false

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
    - RUBY_VERSION: 26
    - RUBY_VERSION: 27
    - RUBY_VERSION: 30
    - RUBY_VERSION: 31

install:
  - set PATH=C:\Ruby%RUBY_VERSION%-x64\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

environment:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
