desc "Run the EditorRun.Build task"
lane :u3d_build do |options|
  raw_logs = !!options[:raw_logs]
  u3d(raw_logs: options[:raw_logs], run_args: "-logFile './editor.log' -executeMethod U3d.EditorRun.Build -quit -batchmode")
end
