source 'https://rubygems.org'

gem 'fastlane'
FASTGAME_REPO_ROOT = File.expand_path(File.join('..', '..'))
gem 'u3d', :path => File.join(FASTGAME_REPO_ROOT, 'u3d')

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)