name: CI
on: [push, pull_request]
jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        ruby: [ 2.6, 2.7, 3.0.7, 3.1, 3.2, 3.3 ] # somehow github uses ruby 3.3 when specifying 3.0
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: git config autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows'

    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run specs (Linux)
      if: matrix.os == 'ubuntu'
      run: bundle exec rake

    - name: Run specs (macOS)
      if: matrix.os == 'macos'
      run: bundle exec rake

    - name: Run specs (Windows)
      if: matrix.os == 'windows'
      run: bundle exec rake
        # Actions uses UTF8, causes test failures, similar to normal OS setup
        #[Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("IBM437")
        #[Console]::InputEncoding  = [System.Text.Encoding]::GetEncoding("IBM437")
